"""
Django settings for mutts project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os 
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()  # Loads .env into os.environ



#DEBUG = os.getenv("DEBUG", "False") == "True"
DEBUG = "True"

SECRET_KEY = os.getenv("SECRET_KEY", "fallback_key_for_debug")


ALLOWED_HOSTS = [

    "127.0.0.1",
    "localhost",
    "lojinhamutts2025.vercel.app",
    "lojinhamutts2025-git-main-dani-valois-projects.vercel.app",
    "lojinhamutts2025-6ah3ghlql-dani-valois-projects.vercel.app",  
    ".vercel.app",
    "*.supabase.co"
]

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL")
    )
}




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Example: 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apln2911@gmail.com'
EMAIL_HOST_PASSWORD = 'tjaqarfoambxbnat'  # Use environment variables for security!
DEFAULT_FROM_EMAIL = 'apln2911@gmail.com'


SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'customers',
    'orders',
    'checkouts',
    'accounts',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mutts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 
            'templates', 
            'C:/users/apln2/dropbox/mutts_website/mutts/templates',
            'C:/users/apln2/dropbox/mutts_website/mutts/products/templates/products',
            'C:/users/apln2/dropbox/mutts_website/mutts/customers/templates/customers',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]






WSGI_APPLICATION = 'mutts.wsgi.application'




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

THOUSAND_SEPARATOR='.',
USE_THOUSAND_SEPARATOR=True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, ('assets')),
)


STATIC_ROOT = os.path.join(BASE_DIR, 'C:/Users/apln2/Dropbox/Mutts_Website/staticfiles')


SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
SUPABASE_BUCKET = os.getenv('SUPABASE_BUCKET', 'product-images')
SUPABASE_PATH_PREFIX = 'products/'  # Or whatever folder inside bucket
MEDIA_URL = f"{SUPABASE_URL}/storage/v1/object/public/{SUPABASE_BUCKET}/{SUPABASE_PATH_PREFIX}"




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FILE_STORAGE = "mutts.supabase_storage_backend.SupabaseStorage"

