BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXX XXXX XXX XXXX XX XXXXXX   XXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB
