BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XX XXXXXXXXXXXXXX
XXXXXX  

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    X 
                    X 
                     X 
                    X
                XXXXXX
                XXXX XXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBB 
                          
                        BBBB
                        XXXXXXXXX XXX XXXXXXXXXXXXXXXX
                        BBBBB 

                XXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        BBBBBB
    XXXXXX
XXXXXX

BBBBBBBB

