# Generated by Django 5.1.6 on 2025-02-20 21:34

import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_zip_code', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('customer_street', models.CharField(max_length=255)),
                ('customer_neighborhood', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_state', models.CharField(max_length=2)),
                ('customer_house_number', models.CharField(max_length=10)),
                ('customer_complement', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('customer_created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_updated_at', models.DateTimeField(auto_now=True)),
                ('customer_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('house_number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
        ),
    ]
