# Generated by Django 5.1.6 on 2025-02-28 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_complement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_house_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_neighborhood',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_street',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='customer_city',
            field=models.CharField(default='Rio de Janeiro', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_complement',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_email',
            field=models.EmailField(blank=True, default='antonio.leitao@gmail.com', max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_house_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_neighborhood',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_phone',
            field=models.CharField(blank=True, default='0', max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_state',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_street',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_zip_code',
            field=models.CharField(default='22793084', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
    ]
