# Generated by Django 5.1.6 on 2025-03-01 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_address_city_remove_address_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_house_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_neighborhood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_zip_code',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
    ]
