# Generated by Django 5.1.6 on 2025-03-01 20:22

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_address_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer_zip_code',
            field=models.CharField(max_length=9, validators=[customers.models.validate_zip_code], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_cpf',
            field=models.CharField(max_length=11, unique=True, validators=[customers.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
