BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBXX
        XXXXX XXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX

 
      XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXXX
      XXXXXX


      XXXX XXXXXXXXXXXXXXXX
        BBBBB BBBBBBB
        BBBBBBBB
      XXXXXX

      XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX
                XXXX
            XXXXX
        XXXXX
    XXXXXXXXX






  XXXXXXX
  
XXXXXXX