BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XX XXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB

            BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                        BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
                            BBB BBBBB BB BBBBBB
                                XXXXX XXXXX
                            BBBBBB
                        BBBBBB
                    XXXXX
                XXXXXX
            BBBBB

              

            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
BBBBBBBB