BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX X XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXX XXXX XXX XXXX XX XXXXXX   XXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB
