# Generated by Django 5.1.6 on 2025-03-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_address_customer'),
        ('orders', '0001_initial'),
        ('products', '0004_alter_product_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_complement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_house_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_neighborhood',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_unit_price',
            field=models.DecimalField(decimal_places=2, default='0.01', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_freight_cost',
            field=models.DecimalField(decimal_places=2, default='0.01', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(max_length=50),
        ),
    ]
