# Generated by Django 5.1.6 on 2025-03-03 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_customer_remove_order_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_service', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_freight_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.freight'),
        ),
    ]
