# Generated by Django 5.1.6 on 2025-03-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_freight_alter_order_order_freight_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_leadtime',
            field=models.IntegerField(null=True),
        ),
    ]
