# Generated by Django 5.1.6 on 2025-03-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pmt_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
