# Generated by Django 5.1.6 on 2025-03-28 21:32

import mutts.supabase_storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.ImageField(blank=True, null=True, storage=mutts.supabase_storage_backend.SupabaseStorage, upload_to=''),
        ),
    ]
