# Generated by Django 5.1.6 on 2025-03-28 23:43

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_jpg]),
        ),
    ]
