# Generated by Django 5.1.6 on 2025-03-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.CharField(blank=True, help_text='This should be a full public URL to the image in Supabase.', max_length=500, null=True),
        ),
    ]
